// lib/features/emr/emr_timeline.dart
import 'package:flutter/material.dart';
import 'package:flutter_animate/flutter_animate.dart';
import '../../core/theme/app_colors.dart';
import '../../core/widgets/common_widgets.dart';

class EmrTimeline extends StatelessWidget {
  const EmrTimeline({super.key});

  static const _records = [
    _EmrRecord('Mar 22, 2024', 'Screening', 'Myopia with Astigmatism detected at Eye Camp, Nuzvid', AppColors.screeningTeamColor, Icons.remove_red_eye_rounded),
    _EmrRecord('Mar 22, 2024', 'Prescription', 'Prescription generated by Dr. Venkata Rao. Right: -2.50/-0.75/180°, Left: -2.25/-0.50/175°', AppColors.primaryBlue, Icons.description_rounded),
    _EmrRecord('Mar 23, 2024', 'Approval', 'Prescription approved by Nodal Officer, Krishna District', AppColors.nodalOfficerColor, Icons.approval_rounded),
    _EmrRecord('Mar 24, 2024', 'Vendor Assignment', 'Order assigned to Sri Opticals, Vijayawada. Expected delivery: 30 Mar 2024', AppColors.vendorColor, Icons.storefront_rounded),
    _EmrRecord('Mar 24, 2024', 'Teleconsultation', 'Video consultation with Dr. Anita Rao (SVIMS). Duration: 18 mins. Follow-up: 6 months', AppColors.teleDocColor, Icons.video_call_rounded),
    _EmrRecord('Mar 28, 2024', 'Spectacles Delivered', 'Spectacles delivered by Sri Opticals. OTP verified. GPS confirmed. Patient satisfied.', AppColors.success, Icons.home_rounded),
    _EmrRecord('Mar 28, 2024', 'Referral', 'Referred to Tirumala Hospital for Fundus evaluation of mild DR changes', AppColors.warning, Icons.local_hospital_rounded),
  ];

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    return Scaffold(
      appBar: AppBar(
        title: const Text('Electronic Medical Record'),
        backgroundColor: AppColors.primaryBlue,
        leading: const AppBarBackButton(),
        actions: [
          IconButton(icon: const Icon(Icons.download_rounded), onPressed: () {}),
          IconButton(icon: const Icon(Icons.share_rounded), onPressed: () {}),
        ],
      ),
      body: Column(
        children: [
          // Patient summary header
          Container(
            padding: const EdgeInsets.all(16),
            color: AppColors.primaryBlue.withOpacity(0.06),
            child: Row(
              children: [
                CircleAvatar(
                  radius: 28,
                  backgroundColor: AppColors.primaryBlue.withOpacity(0.15),
                  child: const Text('RK', style: TextStyle(fontWeight: FontWeight.w900, color: AppColors.primaryBlue, fontSize: 18)),
                ),
                const SizedBox(width: 12),
                Expanded(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text('Ravi Kumar Reddy', style: theme.textTheme.titleMedium?.copyWith(fontWeight: FontWeight.w800)),
                      Text('45y • Male • 9876543210', style: theme.textTheme.bodySmall?.copyWith(color: Colors.grey[600])),
                      Text('ABHA: 14-3456-7890-1234', style: theme.textTheme.bodySmall?.copyWith(color: AppColors.primaryBlue)),
                    ],
                  ),
                ),
                StatusBadge(label: 'Active'),
              ],
            ),
          ),

          // Timeline
          Expanded(
            child: ListView.builder(
              padding: const EdgeInsets.all(16),
              itemCount: _records.length,
              itemBuilder: (context, i) {
                final record = _records[i];
                final isLast = i == _records.length - 1;

                return Row(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    // Left timeline
                    SizedBox(
                      width: 50,
                      child: Column(
                        children: [
                          Container(
                            width: 36,
                            height: 36,
                            decoration: BoxDecoration(
                              color: record.color.withOpacity(0.12),
                              shape: BoxShape.circle,
                              border: Border.all(color: record.color, width: 2),
                            ),
                            child: Icon(record.icon, size: 16, color: record.color),
                          ),
                          if (!isLast)
                            Container(
                              width: 2,
                              height: 60,
                              margin: const EdgeInsets.symmetric(vertical: 4),
                              decoration: BoxDecoration(
                                gradient: LinearGradient(
                                  begin: Alignment.topCenter,
                                  end: Alignment.bottomCenter,
                                  colors: [record.color.withOpacity(0.5), Colors.grey.withOpacity(0.2)],
                                ),
                              ),
                            ),
                        ],
                      ),
                    ),

                    const SizedBox(width: 12),

                    // Content
                    Expanded(
                      child: Padding(
                        padding: const EdgeInsets.only(bottom: 16),
                        child: Card(
                          child: Padding(
                            padding: const EdgeInsets.all(14),
                            child: Column(
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: [
                                Row(
                                  children: [
                                    Container(
                                      padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 2),
                                      decoration: BoxDecoration(
                                        color: record.color.withOpacity(0.1),
                                        borderRadius: BorderRadius.circular(4),
                                      ),
                                      child: Text(
                                        record.type,
                                        style: TextStyle(
                                          color: record.color,
                                          fontSize: 10,
                                          fontWeight: FontWeight.w700,
                                        ),
                                      ),
                                    ),
                                    const Spacer(),
                                    Text(record.date, style: TextStyle(color: Colors.grey[500], fontSize: 10)),
                                  ],
                                ),
                                const SizedBox(height: 8),
                                Text(record.details, style: theme.textTheme.bodySmall),
                              ],
                            ),
                          ),
                        ),
                      ),
                    ),
                  ],
                ).animate(delay: (i * 80).ms).fadeIn().slideX(begin: -0.1, end: 0);
              },
            ),
          ),
        ],
      ),
    );
  }
}

class _EmrRecord {
  final String date;
  final String type;
  final String details;
  final Color color;
  final IconData icon;

  const _EmrRecord(this.date, this.type, this.details, this.color, this.icon);
}
